main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('zombies/', views.zombies_index, name='index'),
  path('zombies/<int:zombie_id>/', views.zombies_detail, name='detail'),
  path('zombies/create/', views.ZombieCreate.as_view(), name='zombies_create'),
  path('zombies/<int:pk>/update/', views.ZombieUpdate.as_view(), name='zombies_update'),
  path('zombies/<int:pk>/delete/', views.ZombieDelete.as_view(), name='zombies_delete'),
  path('zombies/<int:zombie_id>/add_feeding/', views.add_feeding, name='add_feeding'),
  path('zombies/<int:zombie_id>/assoc_wound/<int:wound_id>/', views.assoc_wound, name='assoc_wound'),


]

zombiecollector/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

class Wound(models.Model):
    type = models.CharField(max_length=100)

class Zombie(models.Model):
    # we're defining the columns and constraints on the rows for each column
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    wounds = models.ManyToManyField(Wound)



class Feeding(models.Model):
    date = models.DateField('feeding date')  
  
    meal = models.CharField(
    max_length=1,
    # add the 'choices' field option
    choices=MEALS,
    # set the default value for meal to be 'B'
    default=MEALS[0][0]
  )

zombie = models.ForeignKey(Zombie, on_delete=models.CASCADE)

def __str__(self):
    # Nice method for obtaining the friendly value of a Field.choice
    return f"{self.get_meal_display()} on {self.date}"

def __str__(self):
    return self.name
    
  # Add this method
def get_absolute_url(self):
    return reverse('detail', kwargs={'zombie_id': self.id})

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect

# Add the following import
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Zombie, Wound

from .forms import FeedingForm


# Define the home view
def home(request):
  return HttpResponse('<h1>Brains!</h1>')

def about(request):
  return render(request, 'about.html')

def zombies_index(request):
  zombies = Zombie.objects.all()
  return render(request, 'zombies/index.html', { 'zombies': zombies })

def zombies_detail(request, zombie_id):
  zombie = Zombie.objects.get(id=zombie_id)
  # Get the toys the cat doesn't have
  wounds_zombie_doesnt_have = Wound.objects.exclude(id__in = zombie.wounds.all().values_list('id'))
  feeding_form = FeedingForm()
  return render(request, 'zombies/detail.html', {
    'zombie': zombie, 'feeding_form': feeding_form,
    # Add the toys to be displayed
    'wounds': wounds_zombie_doesnt_have
  })

def add_feeding(request, zombie_id):
  form = FeedingForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_feeding = form.save(commit=False)
    new_feeding.zombie_id = zombie_id
    new_feeding.save()
  return redirect('detail', zombie_id=zombie_id)

def assoc_wound(request, zombie_id, wound_id):
    Zombie.objects.get(id=zombie_id).wounds.add(wound_id)
    return redirect('detail', zombie_id=zombie_id)

class ZombieCreate(CreateView):
  model = Zombie
  fields = '__all__'

class ZombieUpdate(UpdateView):
  model = Zombie
  # Let's disallow the renaming of a cat by excluding the name field!
  fields = ['breed', 'description', 'age']

class ZombieDelete(DeleteView):
  model = Zombie
  success_url = '/zombies/'

main_app/templates/about.html
{% extends 'base.html' %}


{% block content %}
    <h1>About the Zombie Collector</h1>
<hr />
<p>Watch out for zombies!</p>
{% endblock %}

main_app/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Zombie Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;zombiecollector</a></li>
        </ul>
        <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'zombies_create' %}">Add a zombie</a></li>
            <li><a href="{% url 'index' %}">View All My Zombies</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2019 Zombie Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/main_app/zombie_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Zombie</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' zombie.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/zombie_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Cat</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/zombies/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Zombie Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ zombie.name }}</span>
        <p>Breed: {{ zombie.breed }}</p>
        <p>Description: {{ zombie.description }}</p>
        {% if zombie.age > 0 %}
          <p>Age: {{ zombie.age }}</p>
        {% else %}
          <p>Age: baby zombie</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'zombies_update' zombie.id %}">Edit</a>
        <a href="{% url 'zombies_delete' zombie.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_feeding' zombie.id %}" method="post">
   
        {% csrf_token %}
        {{ feeding_form.as_p }}
        <input type="submit" class="btn" value="Add Feeding">
      </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Meal</th></tr>
      </thead>
      <tbody>
        {% for feeding in zombie.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}</td>
            <td>{{feeding.get_meal_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ zombie.name }}'s Wounds</h3>
    {% if zombie.wounds.count %}
      {% for wound in zombie.wounds.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              {{ wound.name }}
            </span>
          </div>
          
        </div>
      {% endfor %}
    {% else %}
      <h5>No Wounds :(</h5>
    {% endif %}
  </div>

  <div class="col s6">
    <h3>Available Wounds</h3>
    {% if wounds.count %}
      {% for wound in wounds.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
          {{wounds.type}}
            </span>
          </div>
          <div class="card-action">
            <form action="" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{zombie.name}} Already Has All wounds Available</h5>
    {% endif %}
  </div>


<script>
const dateEl = document.getElementById('id_date');
M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
});

const selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/zombies/index.html
{% extends 'base.html' %}
{% block content %}

<h1>zombie list</h1>

{% for zombie in zombies %}
  <div class="card">
   <a href="{% url 'detail' zombie.id %}"> <div class="card-content">
      <span class="card-title">{{ zombie.name }}</span>
      <p>Breed: {{ zombie.breed }}</p>
      <p>Description: {{ zombie.description }}</p>
      {% if zombie.age > 0 %}
        <p>Age: {{ zombie.age }}</p>
      {% else %}
        <p>Age: baby zombie</p>
      {% endif %}
    </div>
</a>
  </div>

  
{% endfor %}

{% endblock %}